### PR TITLE
feat: Custom label.

### PR DESCRIPTION
**Pull request by five510**
## Issue
https://github.com/ossf/allstar/issues/44

## Changes
- Open issue with custom label.
  - Override by `IssueLabel` by org/repo allstar.yml.

### CODE REVIEW

**Comment by five510** [comment]
@jeffmendoza 
Could you check it 🙇 ?

**Review by jeffmendoza — CHANGES_REQUESTED** [review]
Everything looks great. I think since the ActionConfig was removed from all the individual policy configs, now configdef.ActionConfig can be removed and config.ActionConfig can be used everywhere.

Do you see anywhere that just using config.ActionConfig will cause problems?

**Comment by jeffmendoza** [comment]
@five510 I was just going to delete configdef then run a configdef -> config find-replace, but ended up changing a bit more.

- I removed ActionConfig. The actions are top-level concepts in Allstar, and don't need to be in sub-parts of config. The OptConfigs are used in all the policies, but this isn't. I usually don't like the idea of passing around structs as parameter lists for functions, preferring to list out all the params if needed in each function.
- I made the issue package call config directly, no need for this to be in the ensure package.
- I moved the label-calculating logic to the issue package. This is specific to issues. Config package is good for helper functions that can be used by multiple policies.
Please take a look and let me know if it looks good. Thanks.

**Review by jeffmendoza — APPROVED** [review]

**Comment by jeffmendoza** [comment]
@asraa Can you do a code review? Thanks.

**Review by asraa — APPROVED** [review]
Thanks! Looks great to me! I tried very hard to nit :P

**Pull request merged**
