### PR TITLE
List the repository for repo config folder before attempting lookup so that cache is utilized

### PR DESCRIPTION
**Pull request by yorinasub17**
This is a follow up to https://github.com/ossf/allstar/pull/192 to improve https://github.com/ossf/allstar/issues/170

When I introduced #192, I inadvertently significantly increased the number of API calls that need to be made, since now for each policy and repo combo, `allstar` needs to make 3 calls: the root org, org repo folder, and the repo `.allstar` folder. This increased the API calls by `5N` (5 policies) where `N` is the number of repos, making it constantly hit the rate limits.

To improve this, this PR adds a check to the config fetching routine that lists the contents of the org level config repo to determine if a folder for the target repo exists there before attempting to fetch it. Normally this would make the situation worse by adding an extra API call. In this case it helps a lot because the request to list the root is cache friendly. That is, that request will be cached and `allstar` will continuously use the cached response during the run across different repos and policies.

In effect, this helped us reduce the number of API calls Allstar made to Github from ~4400 to ~1800.

### CODE REVIEW

**Comment by jeffmendoza** [comment]
I'm curious how getting the directory is more cache friendly than the file. I understand we won't have the file in cache if it is 404, but does GitHub conditional requests not work also?

**Comment by jeffmendoza** [comment]
Did a little testing and confirmed that there is no etag in the 404 response from get repo or get contents. We probably want to abstract getcontents everywhere and have it walk the path from the root of the repo. I'm thinking we probably want to save whether an org has a '.allstar' repo across the enforce run as well.

**Comment by yorinasub17** [comment]
> I'm curious how getting the directory is more cache friendly than the file. I understand we won't have the file in cache if it is 404, but does GitHub conditional requests not work also?

Ah so listing the directory is cache friendly within the loop as `allstar` is working through the repos, vs reusing the cache across multiple iterations of the loop.

The cache key is the URL being requested, so when we list the root directory of `.allstar`, that request is the same no matter what policy or repo we are evaluating. Which means that for all repos, this directory listing request can reuse the response from the first call, and thus avoid a call to the individual file if the repo directory doesn't exist in the first place.

OTOH, even if GitHub caches `404` requests, we would need to make that call for every repo the first time the loop is run to reuse the cache on the next loop, because the URL for the repo config is unique for each repo-policy pair.

Hope that makes sense!

**Comment by yorinasub17** [comment]
Closing as superseded by https://github.com/ossf/allstar/pull/197

**Pull request closed without merging**
