### PR TITLE
Update to github.com/ossf/scorecard/v4

### LINKED ISSUE #70: Upgrade to v3 of scorecard
https://github.com/ossf/allstar/blob/1c2befa6da5151de639ff3145ee95fa64db8ab8b/go.mod#L13

The scorecard version v3 has more reliable features.

### LINKED ISSUE #71: Fix the security advisories
https://deps.dev/go/github.com%2Fossf%2Fallstar

image

### PR DESCRIPTION
**Pull request by justaugustus**
Fixes https://github.com/ossf/allstar/issues/70, fixes https://github.com/ossf/allstar/issues/71.

- go.mod: Update to github.com/ossf/scorecard/v4@v4.0.1
- binary: Update logger methods to use `checker.LogMessage`
- binary: Drop deprecated fields from `checker.CheckRequest`
- binary: Stub SARIF log methods to satisfy `checker.DetailLogger`
- binary: Add `repoLogger` for `githubrepo.CreateGithubRepoClient`
- binary: Fixup `repoClient` args

Signed-off-by: Stephen Augustus <foo@auggie.dev>

xref: https://github.com/ossf/scorecard/issues/1273, https://github.com/ossf/allstar/issues/21

### CODE REVIEW

**Comment by dlorenc** [comment]
Whoa, hey @justaugustus!

**Comment by justaugustus** [comment]
@jeffmendoza @olivekl @naveensrinivasan -- Could you enable CI for this PR? I think it's in a testable state now.

> Whoa, hey @justaugustus!

@dlorenc -- O HAI DERE!

**Comment by justaugustus** [comment]
(Deferring https://github.com/ossf/allstar/issues/21 to another PR, since this wasn't a straightforward bump.)

**Comment by justaugustus** [comment]
Local runs of the CI (note these were run on go1.18beta1):

```console
❯ time docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.41.1 golangci-lint run -v --timeout 10m
```

<details>

```console
Unable to find image 'golangci/golangci-lint:v1.41.1' locally
v1.41.1: Pulling from golangci/golangci-lint
d960726af2be: Already exists
e8d62473a22d: Already exists
8962bc0fad55: Already exists
65d943ee54c1: Already exists
f2253e6fbefa: Already exists
186c77a2a533: Pull complete
db807893dccf: Pull complete
95bcc343b84a: Pull complete
Digest: sha256:33f65c9c685fb6de75a68eaf14a63adeb38da1fbc3e9d13a72915d558c98ad6b
Status: Downloaded newer image for golangci/golangci-lint:v1.41.1
level=info msg="[config_reader] Config search paths: [./ /app / /root]"
level=info msg="[lintersdb] Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck]"
level=info msg="[loader] Go packages loading at mode 575 (deps|files|imports|name|compiled_files|exports_file|types_sizes) took 37.647080086s"
level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 16.598143ms"
level=info msg="[linters context/goanalysis] analyzers took 36.331517699s with top 10 stages: buildir: 29.992915445s, inspect: 1.388798347s, nilness: 967.955791ms, fact_deprecated: 907.305762ms, ctrlflow: 761.679262ms, fact_purity: 669.642622ms, printf: 598.708576ms, typedness: 401.595164ms, SA5012: 401.293368ms, unused: 31.501523ms"
level=info msg="[runner] Issues before processing: 2, after processing: 0"
level=info msg="[runner] Processors filtering stat (out/in): cgo: 2/2, filename_unadjuster: 2/2, skip_files: 2/2, skip_dirs: 2/2, autogenerated_exclude: 2/2, identifier_marker: 2/2, exclude: 2/2, exclude-rules: 0/2, path_prettifier: 2/2"
level=info msg="[runner] processing took 3.514143ms with stages: autogenerated_exclude: 3.094574ms, identifier_marker: 300.985µs, skip_dirs: 46.015µs, path_prettifier: 45.55µs, exclude-rules: 12.886µs, cgo: 2.671µs, nolint: 2.62µs, max_same_issues: 2.028µs, max_per_file_from_linter: 1.589µs, filename_unadjuster: 1.2µs, exclude: 574ns, uniq_by_line: 543ns, max_from_linter: 465ns, diff: 448ns, skip_files: 427ns, path_shortener: 395ns, source_code: 333ns, severity-rules: 300ns, path_prefixer: 283ns, sort_results: 257ns"
level=info msg="[runner] linters took 14.599354549s with stages: goanalysis_metalinter: 14.595140068s"
level=info msg="File cache stats: 0 entries of total size 0B"
level=info msg="Memory: 515 samples, avg is 179.8MB, max is 746.5MB"
level=info msg="Execution took 52.297497108s"
docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.41.1  run -v  0.21s user 0.32s system 0% cpu 1:12.34 total
```

</details>

```console
❯ time go build -v ./...
github.com/gregjones/httpcache
google.golang.org/genproto/googleapis/cloud/secretmanager/v1
gocloud.dev/secrets/driver
gocloud.dev/runtimevar/driver
github.com/ossf/allstar/pkg/policies/branch
github.com/ossf/allstar/pkg/policies/outside
github.com/ossf/allstar/pkg/issue
github.com/ossf/allstar/pkg/policies/security
gocloud.dev/secrets
gocloud.dev/runtimevar
github.com/ossf/allstar/pkg/policies
cloud.google.com/go/secretmanager/apiv1
gocloud.dev/runtimevar/gcpsecretmanager
github.com/ossf/allstar/pkg/ghclients
github.com/ossf/allstar/pkg/enforce
github.com/ossf/allstar/cmd/allstar
go build -v ./...  5.89s user 4.81s system 168% cpu 6.347 total
```

```console
❯ time go test -v ./...
```

<details>

```console
?   	github.com/ossf/allstar/cmd/allstar	[no test files]
=== RUN   TestFetchConfig
=== RUN   TestFetchConfig/OptOutOrg
=== RUN   TestFetchConfig/OptInOrg
=== RUN   TestFetchConfig/IssueLabel
=== RUN   TestFetchConfig/IssueRepo
=== RUN   TestFetchConfig/OptOutRepo
=== RUN   TestFetchConfig/OptInRepo
--- PASS: TestFetchConfig (0.00s)
    --- PASS: TestFetchConfig/OptOutOrg (0.00s)
    --- PASS: TestFetchConfig/OptInOrg (0.00s)
    --- PASS: TestFetchConfig/IssueLabel (0.00s)
    --- PASS: TestFetchConfig/IssueRepo (0.00s)
    --- PASS: TestFetchConfig/OptOutRepo (0.00s)
    --- PASS: TestFetchConfig/OptInRepo (0.00s)
=== RUN   TestIsEnabled
=== RUN   TestIsEnabled/OptInOrg
=== RUN   TestIsEnabled/NoOptInOrg
=== RUN   TestIsEnabled/OptOutOrg
=== RUN   TestIsEnabled/NoOptOutOrg
=== RUN   TestIsEnabled/OptOutPrivateRepos
=== RUN   TestIsEnabled/NoOptOutPrivateRepos
=== RUN   TestIsEnabled/OptOutPublicRepos
=== RUN   TestIsEnabled/NoOptOutPublicRepos
=== RUN   TestIsEnabled/RepoOptIn
=== RUN   TestIsEnabled/RepoOptOut
=== RUN   TestIsEnabled/DissallowOptOut
--- PASS: TestIsEnabled (0.00s)
    --- PASS: TestIsEnabled/OptInOrg (0.00s)
    --- PASS: TestIsEnabled/NoOptInOrg (0.00s)
    --- PASS: TestIsEnabled/OptOutOrg (0.00s)
    --- PASS: TestIsEnabled/NoOptOutOrg (0.00s)
    --- PASS: TestIsEnabled/OptOutPrivateRepos (0.00s)
    --- PASS: TestIsEnabled/NoOptOutPrivateRepos (0.00s)
    --- PASS: TestIsEnabled/OptOutPublicRepos (0.00s)
    --- PASS: TestIsEnabled/NoOptOutPublicRepos (0.00s)
    --- PASS: TestIsEnabled/RepoOptIn (0.00s)
    --- PASS: TestIsEnabled/RepoOptOut (0.00s)
    --- PASS: TestIsEnabled/DissallowOptOut (0.00s)
=== RUN   TestIsBotEnabled
{"level":"info","org":"","repo":"thisrepo","area":"bot","enabled":true,"time":"2022-01-20T10:33:42-05:00","message":"Check repo enabled"}
--- PASS: TestIsBotEnabled (0.00s)
PASS
ok  	github.com/ossf/allstar/pkg/config	0.493s
?   	github.com/ossf/allstar/pkg/config/operator	[no test files]
=== RUN   TestRunPolicies
=== RUN   TestRunPolicies/LogOnly
{"level":"info","org":"","repo":"","area":"Test policy","result":false,"enabled":true,"notify":"","details":null,"time":"2022-01-20T10:33:43-05:00","message":"Policy run result."}
=== RUN   TestRunPolicies/OpenIssue
{"level":"info","org":"","repo":"","area":"Test policy","result":false,"enabled":true,"notify":"","details":null,"time":"2022-01-20T10:33:43-05:00","message":"Policy run result."}
=== RUN   TestRunPolicies/CloseIssue
{"level":"info","org":"","repo":"","area":"Test policy","result":true,"enabled":true,"notify":"","details":null,"time":"2022-01-20T10:33:43-05:00","message":"Policy run result."}
=== RUN   TestRunPolicies/Fix
{"level":"info","org":"","repo":"","area":"Test policy","result":false,"enabled":true,"notify":"","details":null,"time":"2022-01-20T10:33:43-05:00","message":"Policy run result."}
=== RUN   TestRunPolicies/PolicyDisabled
{"level":"info","org":"","repo":"","area":"Test policy","result":false,"enabled":false,"notify":"","details":null,"time":"2022-01-20T10:33:43-05:00","message":"Policy run result."}
--- PASS: TestRunPolicies (0.00s)
    --- PASS: TestRunPolicies/LogOnly (0.00s)
    --- PASS: TestRunPolicies/OpenIssue (0.00s)
    --- PASS: TestRunPolicies/CloseIssue (0.00s)
    --- PASS: TestRunPolicies/Fix (0.00s)
    --- PASS: TestRunPolicies/PolicyDisabled (0.00s)
=== RUN   TestEnforceAll
    enforce_test.go:150: Testing EnforceAll looks tricky, TODO
--- SKIP: TestEnforceAll (0.00s)
PASS
ok  	github.com/ossf/allstar/pkg/enforce	0.631s
=== RUN   TestGet
--- PASS: TestGet (0.00s)
PASS
ok  	github.com/ossf/allstar/pkg/ghclients	0.672s
=== RUN   TestEnsure
=== RUN   TestEnsure/NoIssue
=== RUN   TestEnsure/ClosedIssue
=== RUN   TestEnsure/OpenFreshIssue
=== RUN   TestEnsure/OpenStaleIssue
--- PASS: TestEnsure (0.00s)
    --- PASS: TestEnsure/NoIssue (0.00s)
    --- PASS: TestEnsure/ClosedIssue (0.00s)
    --- PASS: TestEnsure/OpenFreshIssue (0.00s)
    --- PASS: TestEnsure/OpenStaleIssue (0.00s)
=== RUN   TestClose
=== RUN   TestClose/NoIssue
=== RUN   TestClose/ClosedIssue
=== RUN   TestClose/OpenIssue
--- PASS: TestClose (0.00s)
    --- PASS: TestClose/NoIssue (0.00s)
    --- PASS: TestClose/ClosedIssue (0.00s)
    --- PASS: TestClose/OpenIssue (0.00s)
=== RUN   TestLabel
=== RUN   TestLabel/None
=== RUN   TestLabel/Org
=== RUN   TestLabel/Repo1
=== RUN   TestLabel/Repo2
--- PASS: TestLabel (0.00s)
    --- PASS: TestLabel/None (0.00s)
    --- PASS: TestLabel/Org (0.00s)
    --- PASS: TestLabel/Repo1 (0.00s)
    --- PASS: TestLabel/Repo2 (0.00s)
=== RUN   TestRepoTitle
=== RUN   TestRepoTitle/Not_set
=== RUN   TestRepoTitle/Set
--- PASS: TestRepoTitle (0.00s)
    --- PASS: TestRepoTitle/Not_set (0.00s)
    --- PASS: TestRepoTitle/Set (0.00s)
PASS
ok  	github.com/ossf/allstar/pkg/issue	0.327s
?   	github.com/ossf/allstar/pkg/policies	[no test files]
?   	github.com/ossf/allstar/pkg/policies/binary	[no test files]
=== RUN   TestCheck
=== RUN   TestCheck/NotEnabled
{"level":"info","org":"","repo":"thisrepo","area":"Branch Protection","enabled":false,"time":"2022-01-20T10:33:43-05:00","message":"Check repo enabled"}
=== RUN   TestCheck/CatchBlockForce
{"level":"info","org":"","repo":"thisrepo","area":"Branch Protection","enabled":true,"time":"2022-01-20T10:33:43-05:00","message":"Check repo enabled"}
=== RUN   TestCheck/CatchReleaseBranch
{"level":"info","org":"","repo":"thisrepo","area":"Branch Protection","enabled":true,"time":"2022-01-20T10:33:43-05:00","message":"Check repo enabled"}
=== RUN   TestCheck/RepoOverride
{"level":"info","org":"","repo":"thisrepo","area":"Branch Protection","enabled":true,"time":"2022-01-20T10:33:43-05:00","message":"Check repo enabled"}
=== RUN   TestCheck/RepoOverridePrevented
{"level":"info","org":"","repo":"thisrepo","area":"Branch Protection","enabled":true,"time":"2022-01-20T10:33:43-05:00","message":"Check repo enabled"}
=== RUN   TestCheck/NoProtection
{"level":"info","org":"","repo":"thisrepo","area":"Branch Protection","enabled":true,"time":"2022-01-20T10:33:43-05:00","message":"Check repo enabled"}
=== RUN   TestCheck/Emptyrepo
{"level":"info","org":"","repo":"thisrepo","area":"Branch Protection","enabled":true,"time":"2022-01-20T10:33:43-05:00","message":"Check repo enabled"}
--- PASS: TestCheck (0.00s)
    --- PASS: TestCheck/NotEnabled (0.00s)
    --- PASS: TestCheck/CatchBlockForce (0.00s)
    --- PASS: TestCheck/CatchReleaseBranch (0.00s)
    --- PASS: TestCheck/RepoOverride (0.00s)
    --- PASS: TestCheck/RepoOverridePrevented (0.00s)
    --- PASS: TestCheck/NoProtection (0.00s)
    --- PASS: TestCheck/Emptyrepo (0.00s)
=== RUN   TestFix
=== RUN   TestFix/NoChange
=== RUN   TestFix/AddProtection
{"level":"info","org":"","repo":"thisrepo","area":"Branch Protection","time":"2022-01-20T10:33:43-05:00","message":"Updated with Fix aciton."}
=== RUN   TestFix/NotEnabled
=== RUN   TestFix/IncreaseCountAndBlockForce
{"level":"info","org":"","repo":"thisrepo","area":"Branch Protection","time":"2022-01-20T10:33:43-05:00","message":"Updated with Fix aciton."}
=== RUN   TestFix/BlockForceOnly
{"level":"info","org":"","repo":"thisrepo","area":"Branch Protection","time":"2022-01-20T10:33:43-05:00","message":"Updated with Fix aciton."}
--- PASS: TestFix (0.00s)
    --- PASS: TestFix/NoChange (0.00s)
    --- PASS: TestFix/AddProtection (0.00s)
    --- PASS: TestFix/NotEnabled (0.00s)
    --- PASS: TestFix/IncreaseCountAndBlockForce (0.00s)
    --- PASS: TestFix/BlockForceOnly (0.00s)
PASS
ok  	github.com/ossf/allstar/pkg/policies/branch	0.828s
=== RUN   TestCheck
=== RUN   TestCheck/NotEnabled
{"level":"info","org":"","repo":"thisrepo","area":"Outside Collaborators","enabled":false,"time":"2022-01-20T10:33:43-05:00","message":"Check repo enabled"}
=== RUN   TestCheck/NoOC
{"level":"info","org":"","repo":"thisrepo","area":"Outside Collaborators","enabled":true,"time":"2022-01-20T10:33:43-05:00","message":"Check repo enabled"}
=== RUN   TestCheck/Pushers_allowed
{"level":"info","org":"","repo":"thisrepo","area":"Outside Collaborators","enabled":true,"time":"2022-01-20T10:33:43-05:00","message":"Check repo enabled"}
=== RUN   TestCheck/Admin_blocked
{"level":"info","org":"","repo":"thisrepo","area":"Outside Collaborators","enabled":true,"time":"2022-01-20T10:33:43-05:00","message":"Check repo enabled"}
=== RUN   TestCheck/Both_blocked
{"level":"info","org":"","repo":"thisrepo","area":"Outside Collaborators","enabled":true,"time":"2022-01-20T10:33:43-05:00","message":"Check repo enabled"}
=== RUN   TestCheck/Ownerless_blocked
{"level":"info","org":"","repo":"thisrepo","area":"Outside Collaborators","enabled":true,"time":"2022-01-20T10:33:43-05:00","message":"Check repo enabled"}
=== RUN   TestCheck/Ownerless_OK
{"level":"info","org":"","repo":"thisrepo","area":"Outside Collaborators","enabled":true,"time":"2022-01-20T10:33:43-05:00","message":"Check repo enabled"}
--- PASS: TestCheck (0.00s)
    --- PASS: TestCheck/NotEnabled (0.00s)
    --- PASS: TestCheck/NoOC (0.00s)
    --- PASS: TestCheck/Pushers_allowed (0.00s)
    --- PASS: TestCheck/Admin_blocked (0.00s)
    --- PASS: TestCheck/Both_blocked (0.00s)
    --- PASS: TestCheck/Ownerless_blocked (0.00s)
    --- PASS: TestCheck/Ownerless_OK (0.00s)
PASS
ok  	github.com/ossf/allstar/pkg/policies/outside	0.650s
=== RUN   TestCheck
=== RUN   TestCheck/NotEnabled
{"level":"info","org":"","repo":"thisrepo","area":"SECURITY.md","enabled":false,"time":"2022-01-20T10:33:43-05:00","message":"Check repo enabled"}
=== RUN   TestCheck/Pass
{"level":"info","org":"","repo":"thisrepo","area":"SECURITY.md","enabled":true,"time":"2022-01-20T10:33:43-05:00","message":"Check repo enabled"}
=== RUN   TestCheck/Fail
{"level":"info","org":"","repo":"thisrepo","area":"SECURITY.md","enabled":true,"time":"2022-01-20T10:33:43-05:00","message":"Check repo enabled"}
--- PASS: TestCheck (0.00s)
    --- PASS: TestCheck/NotEnabled (0.00s)
    --- PASS: TestCheck/Pass (0.00s)
    --- PASS: TestCheck/Fail (0.00s)
PASS
ok  	github.com/ossf/allstar/pkg/policies/security	1.022s
?   	github.com/ossf/allstar/pkg/policydef	[no test files]
go test -v ./...  10.42s user 7.02s system 403% cpu 4.318 total
```

```console
❯ time go vet ./...
go vet ./...  18.67s user 14.62s system 544% cpu 6.107 total
```

**Review by jeffmendoza — APPROVED** [review]

**Comment by jeffmendoza** [comment]
Looks great, thanks for this. =)

**Comment by justaugustus** [comment]
> Looks great, thanks for this. =)

Happy to help!

**Pull request merged**
