### PR TITLE
update ko to the new home and bump to use v0.13.0 release

### PR DESCRIPTION
**Pull request by cpanato**
- update ko to the new home and bump to use v0.13.0 release

### CODE REVIEW

**Comment by cpanato** [comment]
cc @justaugustus

**Comment by jeffmendoza** [comment]
I think 13 doesn't use the new path yet, need to wait for next version:
```bash
$ go install github.com/ko-build/ko@v0.13.0
go: github.com/ko-build/ko@v0.13.0: github.com/ko-build/ko@v0.13.0: parsing go.mod:
	module declares its path as: github.com/google/ko
	        but was required as: github.com/ko-build/ko
```

**Comment by cpanato** [comment]
> ```shell
> github.com/ko-build/ko
> ```

works for me

```
$ go install github.com/google/ko@v0.13.0
go: downloading github.com/google/ko v0.13.0
go: downloading github.com/google/go-containerregistry v0.13.1-0.20230310164735-e94d40893b2d
go: downloading github.com/awslabs/amazon-ecr-credential-helper/ecr-login v0.0.0-20220517224237-e6f29200ae04
go: downloading k8s.io/apimachinery v0.26.2
go: downloading github.com/dprotaso/go-yit v0.0.0-20220510233725-9ba8df137936
go: downloading github.com/aws/aws-sdk-go-v2/service/ecr v1.17.5
go: downloading github.com/aws/aws-sdk-go-v2/service/ecrpublic v1.13.5
go: downloading google.golang.org/protobuf v1.29.0
go: downloading go.mongodb.org/mongo-driver v1.10.2
go: downloading github.com/BurntSushi/toml v1.1.0

$ ko version
0.13.0
```

**Comment by cpanato** [comment]
> I think 13 doesn't use the new path yet, need to wait for next version:
> 
> ```shell
> $ go install github.com/ko-build/ko@v0.13.0
> go: github.com/ko-build/ko@v0.13.0: github.com/ko-build/ko@v0.13.0: parsing go.mod:
> 	module declares its path as: github.com/google/ko
> 	        but was required as: github.com/ko-build/ko
> ```

set to use the google path and will work upstream to fix this, PTAL

**Comment by jeffmendoza** [comment]
Thanks!!

**Review by jeffmendoza — APPROVED** [review]

**Pull request merged**
