### PR TITLE
Clean up some code in allstar/main

### PR DESCRIPTION
**Pull request by evankanderson**
Minor cleanup while I was reading the code

### CODE REVIEW

**Comment by jeffmendoza** [comment]
Hi Evan, please update the git commit with DCO. Thanks!
https://github.com/ossf/allstar/pull/432/checks?check_run_id=14525693086

**Review by jeffmendoza — APPROVED** [review]

**Comment by Jung47** [comment]
> การล้างข้อมูลเล็กน้อยในขณะที่ฉันกำลังอ่านโค้ด

linked:issue
assignce:USERNAME
is:public
.linked:issue
-author:app/USERNAME
is:private

**Comment by Jung47** [comment]
linked:issue
assignce:USERNAME
is:public
.linked:issue
-author:app/USERNAME
is:private

**Comment by evankanderson** [comment]
(This had fallen into the email update pit until I noticed on a sweep of GitHub notifications this morning; sorry about that!)

**Pull request merged**
