### PR TITLE
New feature: Log summary of enforce results

### PR DESCRIPTION
**Pull request by markdboyd**
This PR adds code to generate a summary of how many repos failed the check for each policy. The summary looks something like this when logged:

```json
 {"severity":"INFO","area":"bot","count":20,
"results":{"Branch Protection":{"totalFailed":3},"Outside Collaborators":{"totalFailed":2}},
"time":"2022-06-09T16:16:23Z","message":"EnforceAll complete."}
```

This feature is useful for me as I configure and test Allstar because it gives me a preview of how many Github issues would be created if I set `action: issue`. It may also be just be a generally useful summary to have.

I also refactored the code slightly to allow unit testing `EnforceAll`.

### CODE REVIEW

**Comment by jeffmendoza** [comment]
Thanks for this! Looks good. Let me do a careful review early next week and we can get this in.

**Review by jeffmendoza — DISMISSED** [review]

**Comment by jeffmendoza** [comment]
@markdboyd LGTM can you rebase and squash? Thanks.

**Comment by markdboyd** [comment]
@jeffmendoza Yeah let me do that now

**Review by jeffmendoza — APPROVED** [review]

**Comment by markdboyd** [comment]
@jeffmendoza Sorry - there was a bad merge in there. I accidentally included the addition of the `PrivateKey` variable in operator.go:

https://github.com/ossf/allstar/pull/204/files#diff-ba47ad507bcb60c3742cd43fa19b772819c7f6737b1e2f3e7f08da2a5c739f94R108

If the next PR is going in shortly, it doesn't matter that much. But my bad.

**Comment by jeffmendoza** [comment]
Ah, no worries. Yes, I'll get that in shortly.

Thanks for all the changes! They will help folks for sure.

Also, FYI I want to namespace the env vars, so this will affect you. Watch out for that whenever you pull in a future rebase. I just created: #208

**Pull request merged**
