### PR TITLE
Updates on CI jobs

### PR DESCRIPTION
**Pull request by cpanato**
- fix dependabot config
- use ko action to install ko
- upgrade to cosign v2

### CODE REVIEW

**Comment by cpanato** [comment]
cc @justaugustus

**Comment by jeffmendoza** [comment]
I want to keep the read-only workflows using major version tag aliases for actions
Yes! I do want to update cosign, thanks for that.

**Comment by cpanato** [comment]
> I want to keep the read-only workflows using major version tag aliases for actions Yes! I do want to update cosign, thanks for that.

major version tags are mutating and we don't know actually what is the actual release, also dependabot can deal with that update, and be will easier for us, but it is your call, want me to drop those things? did that because this is one of the practices that we in ossf advocate for :)

**Comment by jeffmendoza** [comment]
Yep, for read-only workflows it is easier to just use the mutable tag.

**Comment by cpanato** [comment]
@jeffmendoza reverted

**Review by jeffmendoza — APPROVED** [review]

**Pull request merged**
