### PR TITLE
Dependabot settings

### PR DESCRIPTION
**Pull request by naveensrinivasan**
Dependabot settings

### CODE REVIEW

**Review by jeffmendoza — APPROVED** [review]

**Comment by jeffmendoza** [comment]
Looks good, thanks!

Please don't create branches in the main repo. Submit PRs from a fork instead

**Comment by naveensrinivasan** [comment]
> Please don't create branches in the main repo. Submit PRs from a fork instead

Why not create a branch? Could you please explain the reason so that it helps me understand the issue?

**Comment by jeffmendoza** [comment]
Yes, It clutters the main repository with personal branches. It's better if everyone contributes as if they are external contributors. It's even advisable to set your git remotes in your local clone to not be able to push to the main upstream repo, only your fork.  For example, my remotes are set like this:
```
fork	git@github.com:jeffmendoza/allstar.git (fetch)
fork	git@github.com:jeffmendoza/allstar.git (push)
origin	https://github.com/ossf/allstar.git (fetch)
origin	https://github.com/ossf/allstar.git (push)
```
With https for origin, so that I don't accidentally push to the main repo.

**Comment by naveensrinivasan** [comment]
GitHub has a setting to delete branches after merging so you don't have to worry about personal branches that are dangling. 

Also there is branch protection that prevents pushing to the main branch accidentally. 

So I don't see it as an issue.

**Pull request merged**
